---
abstract: 'BeLike::GETTY when you build your dists'
author:
  - 'Torsten Raudssus <torsten@raudss.us> L<http://www.raudss.us/>'
build_requires:
  Test::LoadAllModules: 0.021
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-GETTY
requires:
  App::cpanminus: 1.6002
  Dist::Zilla: 4.300030
  Dist::Zilla::Plugin::Alien: 0.007
  Dist::Zilla::Plugin::Authority: 1.006
  Dist::Zilla::Plugin::BumpVersionFromGit: 0.009
  Dist::Zilla::Plugin::ChangelogFromGit: 0.006
  Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch: 0.006
  Dist::Zilla::Plugin::GithubMeta: 0.28
  Dist::Zilla::Plugin::InstallRelease: 0.008
  Dist::Zilla::Plugin::MakeMaker::SkipInstall: 1.100
  Dist::Zilla::Plugin::PodWeaver: 3.101641
  Dist::Zilla::Plugin::Repository: 0.19
  Dist::Zilla::Plugin::Run: 0.018
  Dist::Zilla::Plugin::TaskWeaver: 0.101624
  Dist::Zilla::Plugin::TravisCI: 0
  Dist::Zilla::Plugin::UploadToDuckPAN: 0.002
  Dist::Zilla::PluginBundle::Git: 2.009
  Pod::Elemental: 0.102362
  Pod::Elemental::Transformer::List: 0.101620
  Pod::Weaver: 3.101638
resources:
  homepage: https://github.com/Getty/p5-dist-zilla-pluginbundle-author-getty
  repository: https://github.com/Getty/p5-dist-zilla-pluginbundle-author-getty.git
version: 0.015
x_Dist_Zilla:
  perl:
    version: 5.016003
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::GETTY/@Basic/GatherDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::GETTY/@Basic/PruneCruft'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::GETTY/@Basic/ManifestSkip'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::GETTY/@Basic/MetaYAML'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::GETTY/@Basic/License'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::GETTY/@Basic/Readme'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::GETTY/@Basic/ExtraTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::GETTY/@Basic/ExecDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::GETTY/@Basic/ShareDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::GETTY/@Basic/MakeMaker'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::GETTY/@Basic/Manifest'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::GETTY/@Basic/TestRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::GETTY/@Basic/ConfirmRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::GETTY/@Basic/UploadToCPAN'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::GETTY/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::GETTY/PkgVersion'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::GETTY/MetaConfig'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::GETTY/MetaJSON'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::GETTY/PodSyntaxTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::GETTY/Repository'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::GETTY/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::TravisCI
      name: '@Author::GETTY/TravisCI'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::GETTY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::GETTY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::GETTY/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Author::GETTY/TestsOfAuthorGETTY'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: '@Author::GETTY/ChangelogFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::GETTY/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::GETTY/@Git/Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::GETTY/@Git/Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::GETTY/@Git/Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::GETTY/@Git/Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300034
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300034
x_authority: cpan:GETTY
